name: Deploying Pipeline
on: push
env: 
  CONTAINER_REGISTRY: docker.io
jobs:
  build_job_1:
    name: Produce Build Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
  
      - name: Check Files 
        run: ls -ltr

      - name: Activate Script
        run: |
          chmod +x script.sh
          ./script.sh
      
      - name: Check Production of Text File
        run: grep -i "dragon" dragon.txt
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: new-dragon-artifact
          path: dragon.txt

  test_job_2:
    name: Testing files produced in build_job_1
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with: 
        name: new-dragon-artifact
    
    - name: Print Artifact Details
      run: cat dragon.txt
    
    - name: Verify file details
      run: grep -i "dragon" dragon.txt
    
    - name: Print docker username
      run: echo  ${{env.CONTAINER_REGISTRY}}
 
  deploy_job_3:
    name: Deploying the image onto Docker Hub
    runs-on: ubuntu-latest
    needs: [test_job_2]
    steps:
      - name: Build Image
        run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest
      - name: Log into Docker
        run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}
      - name: Publish Docker Image
        run: echo docker push ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest
      - name: Run the Docker image
        run: echo docker run -d -p 8080:80 ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest


